# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GigMeIn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GigMeIn

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'ObjectMapper', '~> 3.1'
pod 'PromiseKit', '~> 6.0'

end
